### ISSUE TITLE
The library should not solely rely on env variables for setting the proxy

### ISSUE THREAD

**Issue by zoltan-fedor** [semi-technologies/weaviate-python-client#103]
Hi team,
Weaviate will likely be used a lot in the enterprise, where it is typical that applications are running behind an web proxy (also known as web gateway).

Currently this library depends on the `requests` module making calls to the Weaviate app - which by default uses the proxy that was set as the environment variable (`HTTTP_PROXY` and `HTTPS_PROXY`) and there is no other way to supply the proxy settings to this library.

Why is this a problem?
Because environment variables are global. So, if in a single script you want to connect to two different services - one which runs locally and doesn't require a proxy and another which runs out on the internet and so it does require a proxy and both rely on the proxy environment variable, then that can't be made to work, as the proxy environment variables are global. So you either set the proxy or you don't by making one or the other service work, but not both at the same time.

To properly solve this, this library should have the option to supply the proxies attribute to the `requests` library, so it doesn't have to only rely on the environment variables for setting the proxy.

Obviously Python clients of other services (databases, APIs, etc) have the same problem (until somebody doesn't raise this point and then they add this option), see this same concern being raised with the Snowflake Python client: https://github.com/snowflakedb/snowflake-connector-python/pull/379#issuecomment-680766882

Here is the link (https://2.python-requests.org/en/master/user/advanced/#proxies) to `requests` library's documentation showing how it supports both the env variable and arguments for setting the proxies, so we just need to bubble up the argument option in this library to allow proper control of the proxy without needing to set the global env variable and causing this whole issue.

**Comment by bobvanluijt** [comment]
Ha - thanks for raising this

**Comment by zoltan-fedor** [comment]
Hi @bobvanluijt 

When I write Python client libraries, I usually do the following in the init of the connection:

```
# Session() in requests automatically does keep-alive, so this can speed up consecutive requests
self.session = requests.Session()

if proxies is not None:
    self.session.proxies = proxies
# also picking the proxies up from the env variables, if they are defined explicitly
elif os.environ.get('http_proxy') is not None \
        or os.environ.get('https_proxy') is not None \
        or os.environ.get('HTTP_PROXY') is not None \
        or os.environ.get('HTTPS_PROXY') is not None:
    self.session.proxies = {
        'http': os.environ.get('http_proxy') if os.environ.get('http_proxy') is not None else os.environ.get('HTTP_PROXY'),
        'https': os.environ.get('https_proxy') if os.environ.get('https_proxy') is not None else os.environ.get('HTTPS_PROXY')
    }
```

This allows you to have the `proxies` argument and still have the environment variable-based setting of the proxy.

Let me know if you want me to make a PR for this.

**Comment by bobvanluijt** [comment]
Looping in @StefanBogdan here :)

**Comment by StefanBogdan** [comment]
Thanks @zoltan-fedor , this is very helpful indeed. At the moment I am working on the next `major` version  of the python client and I think I can add this too. With the new `major` release we want to introduce an async client as well, which means that we will have to use a different library than `requests`, and setting the proxies might be different for the other library. I am thinking of using the `aiohttp` library (if you know something better please let me know), and for it, it looks a bit different ([here](https://docs.aiohttp.org/en/v3.8.1/client_advanced.html#proxy-support) is how they do it).

Either way, I will introduce it, either setting it through an argument and/or method.
