### ISSUE TITLE
Checking WCS instance!

### ISSUE THREAD

**Issue by omarzain27** [semi-technologies/weaviate-python-client#116]
When i try to run python client notebook and authenticate by my account in WCS give me this error at creating a cluster

![problem](https://user-images.githubusercontent.com/87146656/157846711-3b76a631-9123-4711-8711-2839fbbb9cd2.PNG)

**Comment by omarzain27** [comment]
when i try without name it run


![problem2](https://user-images.githubusercontent.com/87146656/157856679-93287bd3-003a-44d0-8582-fb1fb512f039.PNG)

**Comment by bobvanluijt** [comment]
@StefanBogdan – can you maybe help with this?

**Comment by StefanBogdan** [comment]
Hi @omarzain27 we are experiencing some issues with WCS and we are updating it as the moment. Looking back the error I would assume that the name you chose is already taken that is why you are receiving the error that you cannot access the cluster resources. In these kind of situations just try a different name.

**Comment by omarzain27** [comment]
yeah, it works thank you hope this issues solve
