### ISSUE TITLE
Unclosed socket warning when using Python client to upload schema

### ISSUE THREAD

**Issue by Winterflower** [semi-technologies/weaviate-python-client#126]
hey everyone! 
I'm using the Weaviate Python client to create a schema 

```
   client = weaviate.Client('http://localhost:8080')
    client.schema.create(data_dict)
```
and getting the warning below

```
sys:1: ResourceWarning: unclosed <socket.socket fd=3, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 40690), raddr=('127.0.0.1', 8080)>
ResourceWarning: Enable tracemalloc to get the object allocation traceback
```

It's probably not a major issue in terms of resource leakage since one probably doesn't create schemas too often, but thought I'd mention it.

**Comment by bobvanluijt** [comment]
Hmm, interesting, thanks for sharing.

Can you take a look at this @StefanBogdan?

**Comment by StefanBogdan** [comment]
Hi @Winterflower , what version of the python client are you using?

**Comment by Winterflower** [comment]
@StefanBogdan 

```
weaviate-client==3.6.0
```

**Comment by StefanBogdan** [comment]
@Winterflower I tested it and I do not experience it with any Weaviate versions. Can you please provide a full example that I can run?

**Comment by StefanBogdan** [comment]
I could not get this error with any tests, I am going to close this Issue. Please open it if you experience it again.
