### ISSUE TITLE
uuid created batch import does not include dashes & references are not recognised

### ISSUE THREAD

**Issue by databyjp** [semi-technologies/weaviate-python-client#130]
I am not sure if I'm doing something wrong, but the UUID generated by `uuid4().hex' in `weaviate/batch/request.py` (see below snippet) does not include dashes. Consequently the references generated using this does not seem to come up in queries. 

I propose to wrap it around `get_valid_uuid`. (PR to be submitted.)
```python
        if uuid is not None:
            batch_item["id"] = get_valid_uuid(uuid)
        else:
            batch_item["id"] = uuid4().hex
```

**Comment by bobvanluijt** [comment]
@byronvoorbach – can you please align with @StefanBogdan when he's back regarding this issue?

**Comment by bobvanluijt** [comment]
Thanks for the contrib @databyjp
