### ISSUE TITLE
KeyError: 'grant_types_supported' with weaviate.AuthClientCredentials

### ISSUE THREAD

**Issue by kendistiller** [semi-technologies/weaviate-python-client#133]
It seems that the Python client is checking for `client_credentials` in the optional `grant_types_supported` field for the discovery response. 
```
/weaviate/venv/lib/python3.7/site-packages/weaviate/connect/connection.py", line 201, in _set_bearer
    if 'client_credentials' not in request_third_part.json()['grant_types_supported']:
KeyError: 'grant_types_supported'
```
However, our OpenID Connect provider Azure AD does not provide this optional field in its discovery response (apparently).

Yet we are able to authenticate to Weaviate with OIDC via the REST API just fine (and perform read/write), so we would expect the Python client to (hopefully) behave the same.

Here is connection excerpt from the Python client:

```python
client  = weaviate.Client(
    url='http://localhost:8080',
    auth_client_secret=weaviate.AuthClientCredentials(access_token)
)
```

**Comment by dirkkul** [comment]
Hi @kendistiller ,

I think this ([PR](https://github.com/semi-technologies/weaviate-python-client/pull/164) and [build](https://github.com/semi-technologies/weaviate-python-client/actions/runs/3567852230)) will fix your issue. You have two possibilities:

- Add the access token you got yourself
```
client = weaviate.Client(
        url=URL, auth_client_secret=weaviate.AuthBearerConfig(ACCESS_TOKEN)
    )
```
- Let the python client get the access token

```
client = weaviate.Client(
        url=URL, auth_client_secret=weaviate.AuthClientCredentials(client_secret=CLIENT_SECRET, scope=SCOPE),
    )
```
(We have a hardcoded scope for azure. But if you supply one, yours has precedent.)

**Comment by dirkkul** [comment]
merged, please let us know if this doesn't fix your error
