### ISSUE TITLE
Querying weaviate using GQL pattern discussion

### ISSUE THREAD

**Issue by fefi42** [semi-technologies/weaviate-python-client#18]
Currently the client allows a very simple query that is basically just a POST of a graphql query to weaviate. Users might want to build more complex GQL queries and might not want to use just (hard coded) strings. Creating string based queries also has the risk of creating queries vulnerable to injections.

The problem here is that while the REST API is very easily useable in python, GQL is not. Thats because json's can be represented seamlessly as native python objects while GQL can not. I would like to have a discussion on how to approach this. 

One suggestion would be to recommend a GQL python client to the users and add support for that in our client. This would prevent us from implementing any GQL specific standards ourself. 

Any opinions about this? @bobvanluijt @etiennedi @laura-ham

**Comment by bobvanluijt** [comment]
I think that something like this:

```py
query = """{
 Get {
   Things {
     Article {
       title
     }
   }
 } 
}"""

result = weaviate_client().GQL(query)
```

For now, is already enough. It is just a simple way for people to get a result from a Weaviate.

**Comment by fefi42** [comment]
> I think that something like this:
That is what we have currently `query(gql_query)`

I think that this is not the best solution in the long term tough. Because it invites to do something like this: 

```python
explore = """
{
  Get {
    Things {
      Article (explore: {
        concepts: [\"%s\"],
      }){
      title
        }
      }
    }
  }
}
"""
result = client.query((explore % user_search_terms))
```

**Comment by bobvanluijt** [comment]
Aha, I see. But because people use it for their own Weaviates, this might be less of a problem for now.

Can this issue be closed?

**Comment by fefi42** [comment]
I wouldn't close this issue. I would rather leave it open and discuss how we can for the future prevent anti-patterns like the one above.

**Comment by bobvanluijt** [comment]
Sounds good

**Comment by etiennedi** [comment]
I remember starting to write a response to this some time over the weekend, but looks like I never sent it.

Basically I'm not sure if it's so bad that GQL is essentially just string manipulation. Let's say you have a SQL database, no matter how sophisticated the client is, aren't you still building a SQL statement as a string in the end? Of course there are things like prepared statements to prevent injections, etc. But it still builds a string? 

If we start building a high-level abstraction, don't we lose the benefits of GraphQL? Let's say we have something like: (this is probably not valid python, treat it as pseudo code)

```python
result = client.query
  .withKind("thing")
  .withClass("Article")
  .withProperty("titile")
  .withExplore({ concepts: ["foo", "bar"] })
  .do()
```

we have an effective query builder. But at the same time we lose one of the major benefits of graphQL for not-strictly typed languages: WIth a GQL query string you define the return strucutre. I.e. by writing `{ Get { Things { Article { name  } } } }`, you know that you'll get exactly an object where `Get.Things[].Article.name` is a valid object structure. With my query builder above, while comfortable to use, you have no idea how to access your data (for example you could switch around the order of `withKind()` and `withClass` in the builder, but the return structure wouldn't change.

So, I'd argue if the user prefers the comfort of building a query with a fancy typed builder, they'll probably be better off with the REST api, where the response is a plain object or a list of plain objects (predictable). Whereas GQL shines about defining the result structure as part of the query - especially if references go many levels deep. (Having said that, I know that the REST API does not have feature parity with GQL at the moment, but this would just be another argument to actively would on getting to similar capabilities in both APIs).

**Comment by fefi42** [comment]
> aren't you still building a SQL statement as a string in the end?

As far as I know there this is not done for bigger products in modern libraries, instead they generate a database native statement that does not have to be parsed anymore. 

> If we start building a high-level abstraction, don't we lose the benefits of GraphQL?

I don't want to build a high level abstraction of GraphQL. I thought maybe we can just support other abstraction libraries and build a connector for them.

> this would just be another argument to actively work on getting to similar capabilities in both APIs

In python I would always prefer json over GraphQL. If this is part of the road map then I would wait for this.

**Comment by etiennedi** [comment]
On "How to get variables into the GQL strings, here's how the Apollo JS client handles this. This is quite simple and straight forward in my opinion: https://www.apollographql.com/docs/react/data/queries/#caching-query-results

I assume there's an equivalent in Python. So I'd basically vote for including a client with such capabilities and making that client easy to use from the library - rather than buidling something that is a weaviate-specific GQL client. 

---

> I thought maybe we can just support other abstraction libraries and build a connector for them.
Agreed, just saw this response coming in while I was typing the above :)

---

> In python I would always prefer json over GraphQL. If this is part of the road map then I would wait for this.

Not really, it's more a pet peeve of mine that REST doesn't have explore search, etc., but I haven't justified working on this since it didn't block anyone or anything. Feel free to open an issue for features you're missing from the REST API and we can take the discussion there.

**Comment by fefi42** [comment]
For simple GQL queries a builder was added.
For complex GQL (inline fragments) are only possible over raw queries.
