### ISSUE TITLE
add_reference_to_thing doesn't need URL while batching

### ISSUE THREAD

**Issue by bobvanluijt** [semi-technologies/weaviate-python-client#25]
Currently, a batch is done like this: `client.add_reference_to_thing("2db436b5-0557-5016-9c5f-531412adf9c6", "members", "b36268d4-a6b5-5274-985f-45f13ce0c642")`

However, in all other situations, a beacon (or CREF) is always set as a URL which might be confusing.

The suggestion is to add the function: `add_reference()` which behaves the exact same way but with the URLs: `client.add_reference("weaviate://localhost/things/2db436b5-0557-5016-9c5f-531412adf9c6", "members", "weaviate://localhost/things/b36268d4-a6b5-5274-985f-45f13ce0c642")`

In the documentation, I would like then also to focus on `add_reference()` for consistency.

**Comment by fefi42** [comment]
We can keep it in the same function and just convert it internally so it does not matter which one you use
