### ISSUE TITLE
Async classification polling in Python client

### ISSUE THREAD

**Issue by upasana-mittal** [semi-technologies/weaviate-python-client#28]
> Can we have async poling functionality while doing classification? Currently it gives a UUID against which we have to trigger another endpoint and keep checking status.

**Comment by bobvanluijt** [comment]
Great idea, thanks @upasana-mittal 

@fefi42 would it be possible to make this a sync function when classification I added to the Pythonlib?

**Comment by fefi42** [comment]
The configuration builder has a wait for completion option since `1.0.0`.

https://www.semi.technology/documentation/weaviate/current/restful-api-references/classification.html#start-a-knn-classification
