### ISSUE TITLE
Examples in docs not aligned with other docs

### ISSUE THREAD

**Issue by bobvanluijt** [semi-technologies/weaviate-python-client#38]
For consistency, all documentation is based on the news article dataset. The [current Python docs](https://www.semi.technology/documentation/weaviate/current/client-libs/python.html) however aren't.

It would be great if they can be aligned with the other docs.

**Comment by fefi42** [comment]
https://github.com/semi-technologies/semi-website/pull/540

**Comment by fefi42** [comment]
Docs are now based on articles
