### ISSUE TITLE
Allow for basic CRUD and DDL functionality to work along example or tutorial.

### ISSUE THREAD

**Issue by WolfgangFahl** [semi-technologies/weaviate-python-client#39]
https://travis-ci.org/github/WolfgangFahl/DgraphAndWeaviateTest has test code for Dgraph and Weaviate. While it was relatively straight forward to get the Dgraph unit tests at https://github.com/WolfgangFahl/DgraphAndWeaviateTest/blob/master/tests/testDgraph.py working based on the tutorial https://dgraph.io/tour/ and sample code  https://github.com/dgraph-io/pydgraph/blob/master/examples/simple/simple.py the unit tests in:

https://github.com/WolfgangFahl/DgraphAndWeaviateTest/blob/master/tests/testWeaviate.py

do not work out of the box yet. The port will have to be modified since it's also used by dgraph - the docker image will have to be pulled and started and there is a need for a drop_all functionality as in the dgraph example. Otherwise it should be possible to write a weaviate simple/wrapper code as https://github.com/WolfgangFahl/DgraphAndWeaviateTest/blob/master/dg/simple.py was derived from the  https://github.com/dgraph-io/pydgraph/blob/master/examples/simple/simple.py  code. '

For the startup via docker issues see also https://stackoverflow.com/questions/63260073/starting-zero-alpha-and-ratel-in-a-single-command-e-g-in-macosx-and-other-envir

**Comment by fefi42** [comment]
All CRUD and DDL functions are available from version `1.0.0` onwards.

**Comment by WolfgangFahl** [comment]
Please reopen until the DgraphAndWeaviate Unit test run again. With the incompatible API changes: https://travis-ci.org/github/WolfgangFahl/DgraphAndWeaviateTest/jobs/729050503 fails and I don't know how to refactor things to get them working aain.
