### ISSUE TITLE
Accept url to json schema parameter in "schema.contains()"

### ISSUE THREAD

**Issue by laura-ham** [semi-technologies/weaviate-python-client#40]
`schema.create()` accepts a dict as well as url to a json file. A similar function `schema.contains()` does not support an url to a json schema file as parameter. Suggested is to accept also an url in the `schema.contains()` function for consistency and for convenience. For example: 

```python
import weaviate
w = weaviate.Client("http://localhost:8080")

contains_people_schema = w.schema.contains("https://raw.githubusercontent.com/semi-technologies/weaviate-python-client/master/documentation/getting_started/people_schema.json")
print(contains_people_schema)

# similar to
w.schema.create("https://raw.githubusercontent.com/semi-technologies/weaviate-python-client/master/documentation/getting_started/people_schema.json")
```

**Comment by fefi42** [comment]
Thanks Ill take care of it.

**Comment by fefi42** [comment]
Forgot to close this. This is now possible in the current release.
