### ISSUE TITLE
Python client not backwards compatible from 2.5.0 to 3.0.0

### ISSUE THREAD

**Issue by bobvanluijt** [semi-technologies/weaviate-python-client#61]
I've updated the python client from 2.5.0 to 3.0.0

This results in:

```
Traceback (most recent call last):
  File "/Users/[path]/./load_magento.py", line 6, in <module>
    from modules.schema import create_schema
  File "/Users/[path]/modules/schema.py", line 9, in <module>
    from modules.utilities import DEFAULT_TYPES
  File "/Users/[path]/modules/utilities.py", line 8, in <module>
    from weaviate.tools import WCS
ModuleNotFoundError: No module named 'weaviate.tools'
```

**Comment by StefanBogdan** [comment]
@bobvanluijt  Version 3.0.0 is NOT backwards compatible, I have removed some things and renamed them to more appropriate names. This means that the code needs some adjustments. `WCS` is now located in `weaviate.wcs`.

**Comment by StefanBogdan** [comment]
The reason for this is because I removed some legacy code and made it a bit more optimised and faster.

**Comment by bobvanluijt** [comment]
Ok - is this clearly mentioned in _all_ the docs?

**Comment by StefanBogdan** [comment]
The changelogs contain all the information, [here](https://weaviate-python-client.readthedocs.io/en/latest/changelog.html) and [here](https://www.semi.technology/developers/weaviate/current/client-libraries/python.html#300).

Let me know if it is not clear from this sources, then we can add more examples to the docs.

With this I close this issue.
